DATABASE_PATH = "data/recommender.db"
MODEL_PATH = "data/model.pkl"
FAISS_INDEX_PATH = "data/faiss.index"
SASREC_MODEL_PATH = "data/sasrec_model.pt"
SASREC_MAP_PATH = "data/sasrec_map.pkl"
COLD_START_THRESHOLD = 3
DEFAULT_N_RECOMMENDATIONS = 10
RETRAIN_THRESHOLD_FEEDBACK = 50
RETRAIN_INTERVAL_SECONDS = 86400  # 24 hours
WEIGHT_RELEVANCE = 1.0
WEIGHT_FRESHNESS = 0.2
WEIGHT_FATIGUE = 0.3
WEIGHT_CONTEXT = 0.4
LATENCY_SLA_ALERT_THRESHOLD_SEC = 0.15
LIGHTGCN_MODEL_PATH = "data/lightgcn.pkl"
BCQ_MODEL_PATH = "data/bcq.pth"
TESTING = False


